# Perfil por defecto
spring.profiles.active=dev

# JPA com�ns
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
# 5 minutos en milisegundos
jwt.access.expiracion=300000
# 7 dias
jwt.refresh.expiration.days=7
jwt.secret=miClaveSecretaMuiLongaParaExploraMap2026Segura1234567890

