# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/explora_map
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=validate
logging.level.org.springframework=ERROR
# Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT:25}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=false
#spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# App
app.base-url=${APP_BASE_URL}
app.verificacion.expiracion-horas=24
