# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/explora_map
spring.datasource.username=explora_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate para PostGIS
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Produción
logging.level.org.springframework=ERROR
spring.jpa.hibernate.ddl-auto=validate
